config/routes.rb
SampleApp::Application.routes.draw do
  

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  match "/", to: 'static_pages#home', via:'get'
  match "/help", to: 'static_pages#help', via:'get'
  match "/about", to: 'static_pages#about', via:'get'
  match "/contact", to: 'static_pages#contact', via:'get'
  match "/signup", to: 'users#new', via:'get'
  match "/signin", to: 'sessions#new', via: 'get'
  match "signout", to:'sessions#destroy', via:'delete'
  match "/hashtag", to: 'hashtag#index', via:'get'
  root 'static_pages#home'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if signed_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>

    <h1>About Us</h1>
    <div class="well col-md-offset-2 col-md-8">
	    <p>
	      JsTwitter is built at <a href="www.jaaga.in/study">Jaaga</a>. Made while learning Rails, not exactly as a product. We hope to make it constantly better. Give a <a href="www.github.com/prank7/sample_app">pull request</a> to improve it.
	    </p>
	</div>
  

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>

    <h1>Contact Us</h1>
   <div class="well col-md-offset-2 col-md-8">
	    <p>
	       Hmmm.... Error! <br><b>Naat Reachable! </b>
	    </p>
	</div>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>

    <h1>Help</h1>
    <div class="well col-md-offset-2 col-md-8">
	    <p>
	      Want Help? Sorry! :P</br>
	      Offering help? Most welcome, Give a <a href="http://www.github.com/prank7/sample_app">pull request</a> to improve it.
	    </p>
	</div>
  

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <div class="row col-md-4">
    <aside class="well">
      <section>
        <%= render 'shared/user_info' %>
      </section>
       <section>
        <%= render 'shared/stats' %>
      </section>
      <section>
        <%= render 'shared/micropost_form' %>
      </section>

    </aside>
     </div>
    <div class="col-md-8">
      <div class="well">
      <h3>Tweet Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
 
<% else %>
<div class="center col-md-offset-1 col-md-6 welcome">
<div class="welcometext">Welcome to JsTwitter</div>
  <div id="myCarousel" class="carousel slide" data-ride="carousel">   
    <!-- Carousel items -->
    <div class="carousel-inner">
        <div class="active item">
            <h3>Share your Thoughts and Discoveries.</h3>
        </div>
        <div class="item">
            <h3>Know the latest announcements.</h3>
        </div>
        <div class="item">
            <h3>Get Mule's latest one-liners!</h3>
        </div>
        <div class="item">
            <h3>Know what technology they are talking about!</h3>
        </div>
        <div class="item">
            <h3><em>"Yash, when are you rolling next? :P"</em></h3>
        </div>
        <div class="item">
            <h3>Checkout what game Ansal is working on.</h2>
        </div>
        <div class="item">
            <h3><em>"Going to Kaggalipura at 6, anyone coming?"</em></h3>
        </div>
        <div class="item">
            <h3>Get Manoj Weather Predictions.</h3>
        </div>
        <div class="item">
            <h3><em>"Hey, They got Baadusha!!"</em></h3>
        </div>
    </div>
</div>
</div>
<div class="col-md-offset-8 well loginbox">
    <h1>Twitter For <%= link_to image_tag "jaaga.jpg", alt: "Jaaga" %> Study</h1>
    <h2>
      See what they are doing at Farmhouse!
    </h2>
<div class="center">
    <%= link_to "Signup Now!", signup_path, class: "btn btn-large btn-primary" %>
    <%= link_to "Login Now!", signin_path, class: "btn btn-large btn-info" %>
</div>
</div>

<% end %>

 